{% set name = "github-to-sqlite" %}
{% set version = "2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/github-to-sqlite-{{ version }}.tar.gz
  sha256: 8dea4b34769ffe425fbac7f776790c1b8b5d976468c64bcd657068b9019bc56a

build:
  entry_points:
    - github-to-sqlite = github_to_sqlite.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml
    - requests
    - sqlite-utils >=2.7.2

test:
  imports:
    - github_to_sqlite
  commands:
    - pip check
    - github-to-sqlite --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dogsheep/github-to-sqlite
  summary: Save data from GitHub to a SQLite database
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - andersy005
